[project]
name = "workmate-tech-task"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.3.5",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pytest-cov>=6.1.1",
    "ruff>=0.11.9",
]
